# Konfiguration fuer behave. Werte hier sind Vorgaben, die Kommandozeilen-
# optionen ueberschreiben duerfen.
# Doku: https://behave.readthedocs.io/en/latest/behave/#configuration-files
[behave]
paths = features
show_timings = false
